skip_tags: true
image:
- Visual Studio 2019
- Ubuntu1804

install: 
  - pwsh: dotnet tool install --global git-flow-version
  - pwsh: dotnet tool install --global coverlet.console


build_script:
  - pwsh: |
        dotnet restore
        dotnet test /p:CollectCoverage=true /p:Exclude=[xunit.*]* /p:CoverletOutput='../../built/DashDashVersion.xml' /p:CoverletOutputFormat=cobertura
        if($env:APPVEYOR_BUILD_WORKER_IMAGE -like "*Visual Studio*")
        {
        $version = git-flow-version.exe --branch $env:APPVEYOR_REPO_BRANCH | ConvertFrom-Json
        }
        else
        {
        $version = git-flow-version --branch $env:APPVEYOR_REPO_BRANCH | ConvertFrom-Json
        }
        Write-Host "calculated version:"
        $version | Format-List
